{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-dockerregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.dockerregistry.server .Values.dockerregistry.username .Values.dockerregistry.password .Values.dockerregistry.email | b64enc | quote }}
{{- end }}