apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt_secret: {{ .Values.secrets.jwtSecret | quote }}
  google_client_secret: {{ .Values.secrets.googleClientSecret | quote }}
  fb_client_secret: {{ .Values.secrets.facebookClientSecret | quote }}
  apple_private_key: {{ .Values.secrets.applePrivateKey | quote }}
  admin_secret_key: {{ .Values.secrets.adminSecretKey | quote }}
  admin_password: {{ .Values.secrets.adminPassword | quote }}