apiVersion: v1
kind: Secret
metadata:
  name: propertyquest-secret
type: opaque
data:
  jwt_secret: eW91ci1zZWNyZXQta2V5
  google_client_secret: WU9VUl9HT09HTEVfQ0xJRU5UX1NFQ1JFVA==
  fb_client_secret: eW91cl9mYWNlYm9va19hcHBfc2VjcmV0
  apple_private_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tbi4uLi5uLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
  admin_secret_key: c2VjcmV0dG9nbw==
  admin_password: MTIzNDU2Nzg=
